### PR TITLE
A node must keep its position relative to its siblings when being renamed

### LINKED ISSUE #255: Node rename changes node position
Contrary to the documentation of the `NodeInterface::rename` API method, when renaming a node in either Doctrine-Dbal or Jackrabbit the _nodes position is changed to that of the last child_.

```
     * Renames this node to the specified newName. The ordering (if any) of
     * this node among it siblings remains unchanged.
```

Although I can't find anything in the actual spec about this

### PR DESCRIPTION
**Pull request by dbu**
Fix #255

Test added in https://github.com/phpcr/phpcr-api-tests/pull/144

### CODE REVIEW

**Comment by dantleech** [comment]
@dbu was this reverted?

**Comment by dbu** [comment]
not that i would be aware of. did the code disapear from master?

**Comment by dantleech** [comment]
no sorry, my mistake. Its fine :) I had git log confusion.

**Comment by hacfi** [comment]
@dbu Nope..all good.

**Pull request merged**
