### PR TITLE
ensure that uuid is not set on node that is not referenceable

### PR DESCRIPTION
**Pull request by dbu**
fix https://github.com/jackalope/jackalope-doctrine-dbal/issues/214

(this is also an issue with jackrabbit in some situations.)

tests are at https://github.com/phpcr/phpcr-api-tests/pull/149

### CODE REVIEW

**Comment by dbu** [comment]
i noticed that this breaks things about the importer test. i have to investigate what we do there.

**Comment by lsmith77** [comment]
this change seems to cause issue with existing tests. got this when running the DBAL test suite with sqlite:

```
There was 1 failure:

1) PHPCR\Tests\Writing\MoveMethodsTest::testWorkspaceMove
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/tests_write_manipulation_move/testWorkspaceMove/srcNode'
+'/tests_write_manipulation_move/testWorkspaceMove/dstNode/srcNode'

/Users/lsmith/htdocs/cmf-sandbox/vendor/jackalope/jackalope-doctrine-dbal/vendor/phpcr/phpcr-api-tests/tests/10_Writing/MoveMethodsTest.php:518
phar:///usr/local/php5-5.5.18-20141103-093354/bin/phpunit/phpunit/TextUI/Command.php:179
phar:///usr/local/php5-5.5.18-20141103-093354/bin/phpunit/phpunit/TextUI/Command.php:132

FAILURES!
Tests: 3340, Assertions: 7703, Failures: 1, Errors: 1, Incomplete: 13, Skipped: 144.
```

**Comment by dbu** [comment]
same with jackrabbit. right now really no clue how that can relate, but will investigate when i find time.

**Comment by dbu** [comment]
this should be fixed now: https://github.com/phpcr/phpcr-api-tests/commit/a6a6d786b8d10eddc94ec5a355c92ea65240590a - we accidentally had an assertion that the move does not change the uuid - that is only true when the moved node is referenceable.

**Comment by dbu** [comment]
just ran the uuid-restrictions with jackalope-doctrine-dbal too, was all green at least locally.

ok to merge this and tests?

**Comment by lsmith77** [comment]
I have merged the tests, and retriggered travis

**Comment by dbu** [comment]
its green!

**Pull request merged**
