### PR TITLE
improve node type validation reporting

### PR DESCRIPTION
**Pull request by dbu**
during debugging, i realized its really hard to find out what triggers a contraint validation error.

### CODE REVIEW

**Comment by danrot** [comment]
I am getting an error on [appveyor](https://ci.appveyor.com/project/sulu/sulu/build/1.0.4446#L796), which seems to be caused by this change...

```
PHP Warning:  Uncaught var_export does not handle circular references
C:\projects\sulu\vendor\symfony\phpunit-bridge\DeprecationErrorHandler.php:73
C:\projects\sulu\vendor\jackalope\jackalope\src\Jackalope\NodeType\NodeType.php:253
C:\projects\sulu\vendor\jackalope\jackalope\src\Jackalope\Node.php:551
C:\projects\sulu\src\Sulu\Component\Content\Document\Subscriber\StructureRemoveSubscriber.php:163
C:\projects\sulu\src\Sulu\Component\Content\Document\Subscriber\StructureRemoveSubscriber.php:136
C:\projects\sulu\src\Sulu\Component\Content\Document\Subscriber\StructureRemoveSubscriber.php:117
C:\projects\sulu\src\Sulu\Component\Content\Document\Subscriber\StructureRemoveSubscriber.php:94
C:\projects\sulu\src\Sulu\Component\Content\Document\Subscriber\StructureRemoveSubscriber.php:82
C:\projects\sulu\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:174
C:\projects\sulu\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:43
C:\projects\sulu\vendor\sulu\document-manag in C:\projects\sulu\vendor\jackalope\jackalope\src\Jackalope\NodeType\NodeType.php on line 253
PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 1572868096 bytes) in C:\projects\sulu\vendor\jackalope\jackalope\src\Jackalope\NodeType\NodeType.php on line 253
```

This only happens on the windows build from appveyor, not on the linux builds on travis. Any ideas? Is this a windows issue? That's probably not caught because there are no windows builds in this repo, right?

**Comment by dbu** [comment]
yeah we don't do windows builds on gitlab-ci. var_export is "only" about reporting information when things go wrong. if you have an idea how to make this less dangerous, i am happy for a pull request. if we reduce the amount of information we can output, i think we have to life with that drawback - better than completely exploding.

**Comment by danrot** [comment]
What do you mean by "better than completely exploding"? It would be better to have the worse exception message but it is not failing like in my case?

And it is also not completely clear to me what this PR does... Which exact information do you need in this place? Hard to make any suggestions without that knowledge...

**Comment by dbu** [comment]
> "better than completely exploding"

avoid to use all memory on a recursion. which not only breaks the process but if it happens on a production could bring the whole server into troubles.

> And it is also not completely clear to me what this PR does.

the idea was to better report what the node type definition allows and what was passed in, when validation failed. i think instead of var_export we could first check if the $value is an array of scalars or something else, and translate that to "nested array" or "array of objects" and only export arrays of scalars.

**Comment by danrot** [comment]
@dbu Created a PR for that: https://github.com/jackalope/jackalope/pull/333

**Pull request merged**
