### PR TITLE
Support PHPUnit 6

### PR DESCRIPTION
**Pull request by gabriel-caruso**
I've tried to add `PHPUnit 6` support, but the `jackalope/jackalope-transport` dependency didn't allow me to run `composer install`. Should we substitute it?

### CODE REVIEW

**Comment by dbu** [comment]
that is a virtual package. when developing, i work in jackalope-doctrine-dbal or jackalope-jackrabbit, which are the two available transport modes. jackalope is only the common core, with implementation for the things phpcr defines. the actual storage engine are dbal resp jackrabbit.

**Comment by dbu** [comment]
in the travis file for this repo, we have `composer remove jackalope/jackalope-transport` to test just the core parts. the real fun is in the -jackrabbit and -dbal repos, where the phpcr-api-tests test suite is run...

**Comment by gabriel-caruso** [comment]
@dbu Oh, okay. The tests did pass, we should be ready to go.

**Comment by dbu** [comment]
great, thanks!

**Pull request merged**
